# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
before_install:
 - export LANG=en_US.UTF-8
 - xcodebuild -sdk -version
 - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
 - pod install --project-directory=Example
script:
 # - set -o pipefail && xcodebuild test -workspace Example/ActivityIndicator.xcworkspace -scheme ActivityIndicatorCI -sdk iphonesimulator8.1 -destination 'name=iPhone 5s,OS=8.1' ONLY_ACTIVE_ARCH=NO | xcpretty -c
 - pod lib lint --quick
